=== mounaqid/Analyyse_sentiment/JEE/XensahForms/src/com/xml/figure.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<!-- Déclaration des element  -->

    <xsd:element name="name" type="xsd:string"/>
    <xsd:element name="color" type="xsd:string"/>
    <xsd:element name="x" type="xsd:double"/>
     <xsd:element name="y" type="xsd:double"/>
      <xsd:element name="x1" type="xsd:double"/>
       <xsd:element name="y1" type="xsd:double"/>
       <xsd:element name="x2" type="xsd:double"/>
       <xsd:element name="y2" type="xsd:double"/>
       <xsd:element name="x3" type="xsd:double"/>
       <xsd:element name="y3" type="xsd:double"/>
       <xsd:element name="height" type="xsd:double"/>
       <xsd:element name="width" type="xsd:double"/>
       <xsd:element name="side" type="xsd:double"/>
       <xsd:element name="cx" type="xsd:double"/>
       <xsd:element name="cy" type="xsd:double"/>
       <xsd:element name="r" type="xsd:double"/>
       
  
      	 <!-- Schéma XML -->
	    <xsd:element name="figure" >
	        <xsd:complexType>
	            <xsd:sequence>
	            
	                   <xsd:element ref="name"   />
	                   <xsd:element ref="color"   />
	                   <xsd:element ref="x"  minOccurs="0" maxOccurs="1" />
	                   <xsd:element ref="y"  minOccurs="0" maxOccurs="1" />
	                   <xsd:element ref="x1"  minOccurs="0" maxOccurs="1" />
	                   <xsd:element ref="y1"  minOccurs="0" maxOccurs="1" />
	                   <xsd:element ref="x2"  minOccurs="0" maxOccurs="1" />
	                   <xsd:element ref="y2"  minOccurs="0" maxOccurs="1" />
	                   <xsd:element ref="x3"  minOccurs="0" maxOccurs="1" />
	                   <xsd:element ref="y3"  minOccurs="0" maxOccurs="1" />
	                   <xsd:element ref="height"  minOccurs="0" maxOccurs="1" />
	                   <xsd:element ref="width"  minOccurs="0" maxOccurs="1" />
	                   <xsd:element ref="cx"  minOccurs="0" maxOccurs="1" />
	                   <xsd:element ref="cy"  minOccurs="0" maxOccurs="1" />
	                    <xsd:element ref="r"  minOccurs="0" maxOccurs="1" />
	                        <xsd:element ref="side"  minOccurs="0" maxOccurs="1" /> 
	            </xsd:sequence>
	            
	            <!-- attribut type -->
	            
	            <xsd:attribute name="type">
	                <xsd:simpleType>
	                    <xsd:restriction base="xsd:string">
	                        <xsd:enumeration value="line"/>
	                        <xsd:enumeration value="rectangle"/>
	                        <xsd:enumeration value="triangle"/>
	                        <xsd:enumeration value="circle"/>
	                        <xsd:enumeration value="square"/>
	                    </xsd:restriction>
	                </xsd:simpleType>
	            </xsd:attribute>
            
	        </xsd:complexType>
	    </xsd:element>
	    
	    <!-- le plan -->
	    <xsd:element name="plan">
       		 <xsd:complexType>
		            <xsd:sequence>
		                <xsd:element ref="figure" maxOccurs="unbounded" />
		            </xsd:sequence>
   		     </xsd:complexType>
    	    </xsd:element>
    	    
</xsd:schema>

=== mounaqid/Analyyse_sentiment/JEE/XensahForms/Plan.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="XensahForms.xsl"?><plan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="figure.xsd">
  <figure type="line">
    <name>l1</name>
    <color>java.awt.Color[r=255,g=255,b=0]</color>
    <x1>10.0</x1>
    <y1>16.0</y1>
    <x2>10.0</x2>
    <y2>16.0</y2>
  </figure>
  <figure type="rectangle">
    <name>rec1</name>
    <color>java.awt.Color[r=255,g=255,b=0]</color>
    <x>10.0</x>
    <y>10.0</y>
    <height>15.0</height>
    <width>16.0</width>
  </figure>
  <figure type="triangle">
    <name>T1</name>
    <color>java.awt.Color[r=64,g=64,b=64]</color>
    <x1>10.0</x1>
    <y1>20.0</y1>
    <x2>10.0</x2>
    <y2>30.0</y2>
    <x3>20.0</x3>
    <y3>30.0</y3>
  </figure>
  <figure type="circle">
    <name>C1</name>
    <color>java.awt.Color[r=255,g=255,b=0]</color>
    <cx>90.0</cx>
    <cy>50.0</cy>
    <r>30.0</r>
  </figure>
  <figure type="square">
    <name>Square1</name>
    <color>java.awt.Color[r=255,g=255,b=0]</color>
    <x>10.0</x>
    <y>10.0</y>
    <side>15.0</side>
  </figure>
</plan>
